### ISSUE TITLE
api失效了？

### ISSUE THREAD

**Issue by ghostsatan** [HuberTRoy/vue-shiyanlou-backend#1]
![image](https://user-images.githubusercontent.com/23454560/68458836-ae141100-023e-11ea-8313-46ba7e2dd3f0.png)

启动项目  启动后台的服务之后 报错了  页面不加载数据

![image](https://user-images.githubusercontent.com/23454560/68458735-7d33dc00-023e-11ea-85e5-381905874006.png)

**Comment by HuberTRoy** [comment]
@ghostsatan 
感谢反馈，实验楼更新了API。

**Comment by ghostsatan** [comment]
> @ghostsatan
> 感谢反馈，实验楼更新了API。

没事   坐等后续更新

**Comment by HuberTRoy** [comment]
@ghostsatan 
实验楼给部分API添加了token认证，补了一个token。
目前尚不清楚token是否有限制。
请重新clone~。

**Comment by HuberTRoy** [comment]
@ghostsatan 
已知限制条件：
会过期。

**Comment by ghostsatan** [comment]
> @ghostsatan
> 已知限制条件：
> 会过期。

那就得定期更换token了。。。  。。。

**Comment by HuberTRoy** [comment]
@ghostsatan 
已修复，自动获取token，请重新clone。
